package com.example.model

import java.util.UUID

enum class PostType {
    FREE,
    PAID
}

enum class PostMediaType {
    IMAGE,
    VIDEO
}

/**
 * A single media item of a feed post, exactly as served by the `get-feed`
 * edge function. Full-resolution signed URLs are ONLY present when the post
 * is viewable (free, own, or unlocked). Locked paid posts carry a tiny
 * `previewUrl` for the blur treatment (images) or nothing (videos).
 */
data class FeedMediaItem(
    val url: String? = null,
    val previewUrl: String? = null,
    val mimeType: String = "image/jpeg",
    val width: Int? = null,
    val height: Int? = null,
    val durationMs: Long? = null
) {
    val isVideo: Boolean get() = mimeType.startsWith("video")
}

data class PostComment(
    val id: String = UUID.randomUUID().toString(),
    val authorId: String = "",
    val authorName: String = "",
    val authorAvatarUrl: String? = null,
    val text: String = "",
    val timestamp: Long = System.currentTimeMillis(),
    val likesCount: Int = 0,
    val isLiked: Boolean = false
)

/**
 * A feed post as stored in the Supabase `feed_posts` table. The id is always
 * generated by the backend — never by the client.
 */
data class FeedPost(
    val id: String = UUID.randomUUID().toString(),
    val authorId: String = "",
    val authorName: String = "",
    val authorUsername: String = "",
    val authorAvatarUrl: String? = null,
    val description: String = "",
    val mediaType: PostMediaType = PostMediaType.IMAGE,
    val postType: PostType = PostType.FREE,
    val priceAmount: Double = 0.0,
    val currency: String = "INR",
    val timestamp: Long = System.currentTimeMillis(),
    val likesCount: Int = 0,
    val isLikedByMe: Boolean = false,
    val commentsCount: Int = 0,
    val comments: List<PostComment> = emptyList(),
    val isUnlocked: Boolean = false,
    val isMine: Boolean = false,
    val isDraft: Boolean = false,
    val mediaUrls: List<String> = emptyList(),
    val lockedPreviewUrls: List<String> = emptyList(),
    val mediaItems: List<FeedMediaItem> = emptyList()
)

/**
 * A currency option from the backend `countries` table (fx rates included).
 */
data class CurrencyOption(
    val code: String,
    val symbol: String?,
    val countryName: String?,
    val fxRate: Double = 1.0
)
