# ============================================================================
# Trigger App — ProGuard / R8 rules
# Generated by audit-E (PROD-AUDIT-1 build/security hardening).
# Keep rules for every library that uses reflection + the app's own data model.
# ============================================================================

# Keep line numbers for crash-stack de-obfuscation in release builds.
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile

# Keep annotations + signatures (needed for reflection-based serialisation,
# generic type discovery, and annotation processors like Room's).
-keepattributes *Annotation*, Signature, InnerClasses, EnclosingMethod

# ----------------------------------------------------------------------------
# Room
# ----------------------------------------------------------------------------
-keep class * extends androidx.room.RoomDatabase { <init>(); }
-keep @androidx.room.Entity class * { *; }
-keepclassmembers class * { @androidx.room.* <methods>; }
-dontwarn androidx.room.paging.**

# ----------------------------------------------------------------------------
# OkHttp
# ----------------------------------------------------------------------------
-dontwarn okhttp3.**
-dontwarn okio.**
-keep class okhttp3.** { *; }
-keep interface okhttp3.** { *; }

# ----------------------------------------------------------------------------
# Coil
# ----------------------------------------------------------------------------
-dontwarn coil.**

# ----------------------------------------------------------------------------
# Agora RTC (native methods + JNI)
# ----------------------------------------------------------------------------
-keep class io.agora.** { *; }
-dontwarn io.agora.**

# ----------------------------------------------------------------------------
# Firebase (FCM service + messaging)
# ----------------------------------------------------------------------------
-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.** { *; }
-dontwarn com.google.firebase.**

# ----------------------------------------------------------------------------
# Kotlinx (coroutines + serialisation)
# ----------------------------------------------------------------------------
-keepclassmembers class kotlinx.coroutines.** { *; }
-dontwarn kotlinx.coroutines.**

# ----------------------------------------------------------------------------
# App data classes — kept verbatim so JSON deserialisation + Room mappings work.
# ----------------------------------------------------------------------------
-keep class com.example.model.** { *; }
-keep class com.example.data.** { *; }
-keep class com.example.service.supabase.** { *; }

# ----------------------------------------------------------------------------
# Enum value helpers (valueOf / values) — used by reflection in many libs.
# ----------------------------------------------------------------------------
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

# ----------------------------------------------------------------------------
# Native methods — must not be renamed (JNI lookup by name).
# ----------------------------------------------------------------------------
-keepclasseswithmembernames class * {
    native <methods>;
}

# ----------------------------------------------------------------------------
# osmdroid (OpenStreetMap map engine — Send Location screen).
# Tile providers, HTTP user-agent negotiation and the location overlays are
# looked up reflectively; upstream guidance is to keep the package intact.
# ----------------------------------------------------------------------------
-keep class org.osmdroid.** { *; }
-dontwarn org.osmdroid.**

# ----------------------------------------------------------------------------
# Razorpay Checkout (WebView-driven payment sheet, JS bridge + reflection)
# ----------------------------------------------------------------------------
-keep class com.razorpay.** { *; }
-dontwarn com.razorpay.**
-keepclassmembers class * { @android.webkit.JavascriptInterface <methods>; }
-keepattributes JavascriptInterface
