-- ============================================================================
-- Trigger App — Feed system (real backend): posts, drafts, unlocks, storage
-- Applied: supabase dashboard SQL editor OR `supabase db push`.
-- Idempotent: safe to re-run.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. countries — reconcile BOTH historical shapes (dial-code table and
--    currency table), then seed the currency columns if missing.
--    (update-fx-rates cron refreshes fx_rate twice daily.)
-- ----------------------------------------------------------------------------
alter table public.countries add column if not exists currency_code   char(3);
alter table public.countries add column if not exists country_name    text;
alter table public.countries add column if not exists iso2            char(2);
alter table public.countries add column if not exists currency_symbol text;
alter table public.countries add column if not exists fx_rate         numeric(20,6) not null default 1.0;
alter table public.countries add column if not exists fx_updated_at   timestamptz;
alter table public.countries add column if not exists currency        char(3);

-- backfill country_name for the dial-code shape where it is null
-- (guarded: the dial-code `name` column may no longer exist if the
--  20260910 currency migration already reshaped the table)
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'countries' and column_name = 'name'
  ) then
    execute 'update public.countries set country_name = name where country_name is null and name is not null';
  end if;
end $$;

-- FULL unique index (NULLs never collide) so ON CONFLICT inference works in
-- every historical table shape — the 20260910 migration may already have a
-- currency_code UNIQUE constraint; a second index is redundant but harmless.
create unique index if not exists countries_currency_code_uniq
  on public.countries (currency_code);

-- currency seed (fx_rate refreshed from exchangerate-api by cron)
insert into public.countries (currency_code, country_name, iso2, currency_symbol, fx_rate)
values
  ('INR','India','IN','₹', 0.012000),
  ('USD','United States','US','$', 1.000000),
  ('EUR','Eurozone','EU','€', 1.080000),
  ('GBP','United Kingdom','GB','£', 1.270000),
  ('AED','United Arab Emirates','AE','د.إ', 0.272000),
  ('AUD','Australia','AU','A$', 0.660000),
  ('CAD','Canada','CA','C$', 0.730000),
  ('SGD','Singapore','SG','S$', 0.740000),
  ('JPY','Japan','JP','¥', 0.006700),
  ('MYR','Malaysia','MY','RM', 0.210000)
on conflict (currency_code) do nothing;

-- ----------------------------------------------------------------------------
-- 2. feed_posts — one table for posts AND drafts (status = draft|published).
--    id is DB-GENERATED (uuid) → "post generated by backend".
-- ----------------------------------------------------------------------------
create table if not exists public.feed_posts (
  id            uuid primary key default gen_random_uuid(),
  author_id     uuid not null references auth.users(id) on delete cascade,
  description   text check (char_length(description) <= 300),
  media_type    text not null default 'image' check (media_type in ('image','video')),
  post_type     text not null default 'free' check (post_type in ('free','paid')),  -- DB-level dropdown
  price_amount  numeric(12,2) not null default 0 check (price_amount >= 0),
  currency      char(3) not null default 'INR',
  status        text not null default 'draft' check (status in ('draft','published')),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  published_at  timestamptz
);

create index if not exists feed_posts_published_idx on public.feed_posts (published_at desc nulls last);
create index if not exists feed_posts_author_idx    on public.feed_posts (author_id, updated_at desc);

drop trigger if exists feed_posts_set_updated_at on public.feed_posts;
create trigger feed_posts_set_updated_at
  before update on public.feed_posts
  for each row execute function public.set_updated_at();

-- ----------------------------------------------------------------------------
-- 3. feed_post_media — ordered media rows; storage paths in the private
--    `feed-media` bucket (path always: {author_id}/{post_id}/{position}.{ext})
-- ----------------------------------------------------------------------------
create table if not exists public.feed_post_media (
  id           uuid primary key default gen_random_uuid(),
  post_id      uuid not null references public.feed_posts(id) on delete cascade,
  position     int  not null default 0,
  storage_path text not null,                 -- path inside feed-media bucket
  mime_type    text not null default 'image/jpeg',
  width        int,
  height       int,
  duration_ms  bigint,
  created_at   timestamptz not null default now(),
  unique (post_id, position)
);

create index if not exists feed_post_media_post_idx on public.feed_post_media (post_id, position);

-- ----------------------------------------------------------------------------
-- 4. post_unlocks — verified Razorpay unlocks (written ONLY by the
--    verify-razorpay-payment edge function via service role).
-- ----------------------------------------------------------------------------
create table if not exists public.post_unlocks (
  id           uuid primary key default gen_random_uuid(),
  post_id      uuid not null references public.feed_posts(id) on delete cascade,
  buyer_id     uuid not null references auth.users(id) on delete cascade,
  creator_id   uuid not null references auth.users(id) on delete cascade,
  amount       numeric(12,2) not null,
  currency     char(3) not null default 'INR',
  payment_id   text not null,
  reference_id text not null unique,
  created_at   timestamptz not null default now(),
  unique (post_id, buyer_id)
);

create index if not exists post_unlocks_buyer_idx on public.post_unlocks (buyer_id);

-- ----------------------------------------------------------------------------
-- 5. RLS
-- ----------------------------------------------------------------------------
alter table public.feed_posts    enable row level security;
alter table public.feed_post_media enable row level security;
alter table public.post_unlocks  enable row level security;

-- posts: everyone authenticated reads PUBLISHED; author has full control of own rows
drop policy if exists "feed_published_read" on public.feed_posts;
create policy "feed_published_read" on public.feed_posts
  for select to authenticated
  using (status = 'published' or author_id = auth.uid());

drop policy if exists "feed_author_insert" on public.feed_posts;
create policy "feed_author_insert" on public.feed_posts
  for insert to authenticated with check (author_id = auth.uid());

drop policy if exists "feed_author_update" on public.feed_posts;
create policy "feed_author_update" on public.feed_posts
  for update to authenticated using (author_id = auth.uid());

drop policy if exists "feed_author_delete" on public.feed_posts;
create policy "feed_author_delete" on public.feed_posts
  for delete to authenticated using (author_id = auth.uid());

-- media rows follow their parent post
drop policy if exists "feed_media_read" on public.feed_post_media;
create policy "feed_media_read" on public.feed_post_media
  for select to authenticated
  using (
    exists (
      select 1 from public.feed_posts p
      where p.id = feed_post_media.post_id
        and (p.status = 'published' or p.author_id = auth.uid())
    )
  );

drop policy if exists "feed_media_author_write" on public.feed_post_media;
create policy "feed_media_author_write" on public.feed_post_media
  for insert to authenticated
  with check (
    exists (select 1 from public.feed_posts p where p.id = post_id and p.author_id = auth.uid())
  );

drop policy if exists "feed_media_author_delete" on public.feed_post_media;
create policy "feed_media_author_delete" on public.feed_post_media
  for delete to authenticated
  using (
    exists (select 1 from public.feed_posts p where p.id = post_id and p.author_id = auth.uid())
  );

-- unlocks: buyer can read own unlocks (creators read via service-role analytics later)
drop policy if exists "post_unlocks_buyer_read" on public.post_unlocks;
create policy "post_unlocks_buyer_read" on public.post_unlocks
  for select to authenticated using (buyer_id = auth.uid());

-- ----------------------------------------------------------------------------
-- 6. Storage — private `feed-media` bucket + policies
-- ----------------------------------------------------------------------------
insert into storage.buckets (id, name, public, file_size_limit)
values ('feed-media', 'feed-media', false, 524288000)   -- 500 MB cap (video)
on conflict (id) do nothing;

-- authenticated users upload ONLY under their own top-level folder
drop policy if exists "feed_media_owner_insert" on storage.objects;
create policy "feed_media_owner_insert" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'feed-media'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "feed_media_owner_delete" on storage.objects;
create policy "feed_media_owner_delete" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'feed-media'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- reads go through signed URLs (service role) — no direct object read policy.

-- ----------------------------------------------------------------------------
-- 7. Grant read on countries to anon too (currency picker pre-login safe)
-- ----------------------------------------------------------------------------
drop policy if exists "countries_public_read" on public.countries;
create policy "countries_public_read" on public.countries
  for select to anon, authenticated using (true);
