// Edge function: save-feed-post
// ----------------------------------------------------------------------------
// Backend gate for ALL feed post writes. The post id is ALWAYS generated by
// the database (gen_random_uuid) — the client never invents one.
//
// Actions:
//   create  — inserts a row (status defaults to 'draft'); returns { postId }
//   update  — patches metadata + (optionally) replaces the media rows
//   publish — validates the post is complete, sets status='published'
//   delete  — removes the post (media rows cascade) + storage objects
//
// Auth: requires a valid Supabase JWT. Ownership enforced server-side.
//
// Request body:
//   { "action": "create" | "update" | "publish" | "delete",
//     "postId"?: string,
//     "description"?: string,          // ≤300 chars, optional (can be blank)
//     "mediaType"?: "image" | "video",
//     "postType"?: "free" | "paid",    // DB-level check constraint
//     "priceAmount"?: number,          // major units
//     "currency"?: string,             // ISO 4217 from public.countries
//     "media"?: [{ "position": int, "storagePath": string,
//                  "mimeType"?: string, "width"?: int, "height"?: int,
//                  "durationMs"?: number }] }
// ----------------------------------------------------------------------------

import { serve } from "https://deno.land/std@0.224.0/http/server.ts";
import { handleOptions, json, errorResponse } from "../_shared/cors.ts";
import {
  createAdminClient,
  resolveUserId,
  resolveStorageServiceKey,
  createAdminClientWithKey,
} from "../_shared/supabase.ts";

interface MediaItem {
  position?: number;
  storagePath?: string;
  mimeType?: string;
  width?: number;
  height?: number;
  durationMs?: number;
}

interface Body {
  action?: string;
  postId?: string;
  description?: string;
  mediaType?: string;
  postType?: string;
  priceAmount?: number;
  currency?: string;
  media?: MediaItem[];
}

const DESCRIPTION_MAX = 300;
const MEDIA_BUCKET = "feed-media";

async function handler(req: Request): Promise<Response> {
  const preflight = handleOptions(req);
  if (preflight) return preflight;
  if (req.method !== "POST") return errorResponse("Method not allowed", 405);

  const authHeader = req.headers.get("Authorization");
  const userId = await resolveUserId(authHeader);
  if (!userId) return errorResponse("Unauthorized", 401);

  let body: Body;
  try {
    body = await req.json();
  } catch {
    return errorResponse("Invalid JSON body", 400);
  }

  const supabase = createAdminClient();
  const action = body.action ?? "";

  // Shared validation --------------------------------------------------------
  if (body.description != null) {
    const d = body.description.trim();
    if (d.length > DESCRIPTION_MAX) {
      return errorResponse(`Description must be ${DESCRIPTION_MAX} characters or fewer`, 422);
    }
  }
  if (body.mediaType != null && !["image", "video"].includes(body.mediaType)) {
    return errorResponse("mediaType must be image or video", 422);
  }
  if (body.postType != null && !["free", "paid"].includes(body.postType)) {
    return errorResponse("postType must be free or paid", 422);
  }
  if (body.postType === "paid") {
    const price = Number(body.priceAmount ?? 0);
    if (!Number.isFinite(price) || price <= 0) {
      return errorResponse("Paid posts require a price greater than zero", 422);
    }
    if (!body.currency || body.currency.length !== 3) {
      return errorResponse("Paid posts require a valid currency code", 422);
    }
    // currency must exist in the countries table (fx/wire source of truth)
    const { data: country } = await supabase
      .from("countries")
      .select("currency_code")
      .eq("currency_code", body.currency.toUpperCase())
      .maybeSingle();
    if (!country) return errorResponse("Unsupported currency", 422);
  }

  function mediaRows(postId: string) {
    return (body.media ?? []).map((m, i) => ({
      post_id: postId,
      position: Number.isFinite(m.position) ? Number(m.position) : i,
      storage_path: (m.storagePath ?? "").replace(/^\/+/, ""),
      mime_type: m.mimeType ?? "image/jpeg",
      width: m.width ?? null,
      height: m.height ?? null,
      duration_ms: m.durationMs ?? null,
    })).filter((m) => m.storage_path.length > 0);
  }

  async function replaceMedia(postId: string) {
    if (body.media == null) return null;
    const rows = mediaRows(postId);
    await supabase.from("feed_post_media").delete().eq("post_id", postId);
    if (rows.length > 0) {
      const { error: mediaError } = await supabase.from("feed_post_media").insert(rows);
      if (mediaError) return errorResponse("Failed to save media: " + mediaError.message, 500);
    }
    return null;
  }

  switch (action) {
    // ------------------------------------------------------------------
    case "create": {
      const insert = {
        author_id: userId,
        description: (body.description ?? "").trim() || null,
        media_type: body.mediaType ?? "image",
        post_type: body.postType ?? "free",
        price_amount: body.postType === "paid" ? Number(body.priceAmount ?? 0) : 0,
        currency: (body.currency ?? "INR").toUpperCase(),
        status: "draft",
      };
      const { data, error } = await supabase
        .from("feed_posts")
        .insert(insert)
        .select("id")
        .single();
      if (error || !data) return errorResponse("Failed to create post: " + (error?.message ?? "?"), 500);

      const mediaErr = await replaceMedia(data.id);
      if (mediaErr) return mediaErr;

      return json({ postId: data.id, status: "draft" });
    }

    // ------------------------------------------------------------------
    case "update": {
      if (!body.postId) return errorResponse("postId is required", 422);
      const { data: post } = await supabase
        .from("feed_posts")
        .select("id, author_id, status")
        .eq("id", body.postId)
        .single();
      if (!post) return errorResponse("Post not found", 404);
      if (post.author_id !== userId) return errorResponse("Not your post", 403);

      const patch: Record<string, unknown> = {};
      if (body.description != null) patch.description = body.description.trim() || null;
      if (body.mediaType != null) patch.media_type = body.mediaType;
      if (body.postType != null) {
        patch.post_type = body.postType;
        patch.price_amount = body.postType === "paid" ? Number(body.priceAmount ?? 0) : 0;
      } else if (body.priceAmount != null) {
        patch.price_amount = Number(body.priceAmount);
      }
      if (body.currency != null) patch.currency = body.currency.toUpperCase();

      if (Object.keys(patch).length > 0) {
        const { error: updErr } = await supabase
          .from("feed_posts")
          .update(patch)
          .eq("id", post.id);
        if (updErr) return errorResponse("Failed to update post: " + updErr.message, 500);
      }

      const mediaErr = await replaceMedia(post.id);
      if (mediaErr) return mediaErr;

      return json({ postId: post.id, status: post.status });
    }

    // ------------------------------------------------------------------
    case "publish": {
      if (!body.postId) return errorResponse("postId is required", 422);
      const { data: post } = await supabase
        .from("feed_posts")
        .select("id, author_id, status, post_type, price_amount")
        .eq("id", body.postId)
        .single();
      if (!post) return errorResponse("Post not found", 404);
      if (post.author_id !== userId) return errorResponse("Not your post", 403);

      // metadata patch first (so a draft can be finalized in the same call)
      const patch: Record<string, unknown> = {};
      if (body.description != null) patch.description = body.description.trim() || null;
      if (body.mediaType != null) patch.media_type = body.mediaType;
      if (body.postType != null) patch.post_type = body.postType;
      if (body.postType === "paid" || (body.postType == null && post.post_type === "paid")) {
        patch.price_amount = Number(body.priceAmount ?? post.price_amount ?? 0);
        if (body.currency) patch.currency = body.currency.toUpperCase();
      }
      if (Object.keys(patch).length > 0) {
        await supabase.from("feed_posts").update(patch).eq("id", post.id);
      }

      const mediaErr = await replaceMedia(post.id);
      if (mediaErr) return mediaErr;

      // completeness check: a published post needs at least one media file
      const { count } = await supabase
        .from("feed_post_media")
        .select("id", { count: "exact", head: true })
        .eq("post_id", post.id);
      if (!count || count < 1) {
        return errorResponse("Attach at least one photo or video before posting", 422);
      }

      const { error: pubErr } = await supabase
        .from("feed_posts")
        .update({ status: "published", published_at: new Date().toISOString() })
        .eq("id", post.id);
      if (pubErr) return errorResponse("Failed to publish: " + pubErr.message, 500);

      return json({ postId: post.id, status: "published" });
    }

    // ------------------------------------------------------------------
    case "delete": {
      if (!body.postId) return errorResponse("postId is required", 422);
      const { data: post } = await supabase
        .from("feed_posts")
        .select("id, author_id")
        .eq("id", body.postId)
        .single();
      if (!post) return errorResponse("Post not found", 404);
      if (post.author_id !== userId) return errorResponse("Not your post", 403);

      // remove storage objects under {authorId}/{postId}/ — the storage API
      // may reject the runtime service key, so bind to a resolved one
      const storageKey = await resolveStorageServiceKey(supabase);
      const storageAdmin = createAdminClientWithKey(storageKey);
      const folder = `${post.author_id}/${post.id}`;
      const { data: objects } = await storageAdmin.storage.from(MEDIA_BUCKET).list(folder, {
        limit: 100,
      });
      if (objects && objects.length > 0) {
        await storageAdmin.storage.from(MEDIA_BUCKET).remove(
          objects.map((o) => `${folder}/${o.name}`),
        );
      }

      const { error: delErr } = await supabase.from("feed_posts").delete().eq("id", post.id);
      if (delErr) return errorResponse("Failed to delete post: " + delErr.message, 500);
      return json({ deleted: true });
    }

    default:
      return errorResponse("action must be create | update | publish | delete", 422);
  }
}

serve(handler, { port: 9031 });
